[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
anchor_student_introduce_program = "E1cVE3QEQmJGz4j7agsM31CrnFUBk8pJmSk8DMe6cUUq"

[programs.devnet]
anchor_student_introduce_program = "E1cVE3QEQmJGz4j7agsM31CrnFUBk8pJmSk8DMe6cUUq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
