[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.devnet]
anchor_movie_review_program = "J7zftNjDgE4wYxQDkLQHZb2mWtmvqgCvfFduSdXagbfU"

[programs.localnet]
anchor_movie_review_program = "J7zftNjDgE4wYxQDkLQHZb2mWtmvqgCvfFduSdXagbfU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
